### ISSUE TITLE
duplicate entry: android/support/compat/R.class

### ISSUE THREAD

**Issue by slott** [satorufujiwara/recyclerview-binder#13]
When using the latest version 2.0.0 compilation breaks:

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/compat/R.class

In my dependencies I have

    compile 'com.android.support:appcompat-v7:26.0.+'
    compile 'com.android.support:recyclerview-v7:26.0.+'
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.5.0'
    compile 'com.google.android.gms:play-services-vision:11.0.4'
    compile 'jp.satorufujiwara:recyclerview-binder:1.3.3'

**Comment by MoyuruAizawa** [comment]
@slott use `2.0.1`

**Comment by satorufujiwara** [comment]
Thank you! I've fixed it.
